"""Install / uninstall the Hermes plugin shim.

Hermes Agent discovers plugins by **scanning folders** at:
  • <hermes_agent>/plugins/memory/<name>/   (bundled — note the memory/ subdir)
  • ~/.hermes/plugins/<name>/                (user-installed — NO memory/ subdir!)

The asymmetry between bundled and user paths is real and surprising —
verified empirically against Hermes v0.10.x in plugins/memory/__init__.py
function `_iter_provider_dirs()` (lines 87-96): it iterates
`user_dir.iterdir()` directly where `user_dir = ~/.hermes/plugins/`.

Hermes does NOT use pip entry_points for memory providers — that loader
has zero references to importlib.metadata. So `pip install memex-hermes`
alone is not enough; Hermes won't see the plugin until something exists
at `~/.hermes/plugins/memex/__init__.py`.

This module ships a thin CLI (`memex-hermes init`) that creates the
required folder + a 3-line shim file that imports from the pip-installed
package. Benefits:

  • Auto-updates: `pip install -U memex-hermes` upgrades the plugin on
    next Hermes restart, without re-running init.
  • Tiny footprint in ~/.hermes/: just a stub, all real code in pip
    site-packages.
  • Passes Hermes' textual scan (looks for `register_memory_provider`
    OR `MemoryProvider` in __init__.py).

Also detects and migrates the (incorrect) 0.1.0 path at
`~/.hermes/plugins/memory/memex/` left over from the pre-publish test
build — moves it to the correct `~/.hermes/plugins/memex/` so retest
without manual `mv` works.

If Hermes adds entry_points support later, the pyproject.toml entry
point declaration is already there for free — no work needed at that
time.
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Optional

from memex_hermes import __version__

log = logging.getLogger(__name__)


SHIM_DIR_NAME = "memex"  # folder name → also the plugin name Hermes sees.

SHIM_INIT_PY = '''"""memex-hermes plugin shim — auto-generated by `memex-hermes init`.

DO NOT EDIT. Re-run `memex-hermes init` to refresh.

This 3-line shim is what Hermes' folder-based plugin discovery loads.
The real implementation lives in the pip-installed `memex_hermes`
package. `pip install -U memex-hermes` upgrades the plugin without
re-running init — the shim picks up the new code automatically.

Hermes textual scan: this file mentions MemoryProvider (via
MemexMemoryProvider import) and register_memory_provider (in this
docstring and in the body of register() below) so the discovery
filter accepts it.
"""

from memex_hermes import register  # noqa: F401
from memex_hermes.provider import MemexMemoryProvider  # noqa: F401

# Generated by memex-hermes v{version}
'''


def _resolve_hermes_home(explicit: Optional[str] = None) -> Path:
    """Find Hermes home dir — explicit arg > $HERMES_HOME > default ~/.hermes/."""
    candidate = (
        explicit
        or os.environ.get("HERMES_HOME")
        or "~/.hermes"
    )
    return Path(os.path.expanduser(candidate)).resolve()


def _shim_path(hermes_home: Path) -> Path:
    """Where the shim must live for Hermes to discover it.

    User-installed plugins go DIRECTLY in ~/.hermes/plugins/<name>/.
    The `memory/` subdir convention is bundled-only — Hermes' loader
    iterates `~/.hermes/plugins/` directly via `_iter_provider_dirs()`.
    """
    return hermes_home / "plugins" / SHIM_DIR_NAME


def _legacy_shim_path(hermes_home: Path) -> Path:
    """Path used by memex-hermes 0.1.0 (wrong — had extra `memory/` subdir).

    Kept for one-time migration: when 0.1.1+ `init` runs, if shim exists
    at this path, we move it to the correct one so users who installed
    0.1.0 don't have to manually `mv` again.
    """
    return hermes_home / "plugins" / "memory" / SHIM_DIR_NAME


def cmd_init(args: argparse.Namespace) -> int:
    """Create the shim folder + __init__.py inside ~/.hermes/plugins/memory/memex/.

    Idempotent: re-running is safe, just rewrites the file with the
    current version stamp.
    """
    hermes_home = _resolve_hermes_home(args.hermes_home)
    if not hermes_home.exists():
        print(
            f"ERROR: Hermes home not found at {hermes_home}.\n"
            "Install Hermes Agent first, or pass --hermes-home /path/to/your/hermes/home",
            file=sys.stderr,
        )
        return 2

    # One-time migration: 0.1.0 created the shim at the wrong path
    # (`plugins/memory/memex/` instead of `plugins/memex/`). Detect and
    # clean up to spare users a manual `mv`. The wrong path was inert —
    # Hermes never read from it — so removing the legacy directory is
    # safe.
    legacy = _legacy_shim_path(hermes_home)
    legacy_migrated = False
    if legacy.exists() and legacy.is_dir():
        shutil.rmtree(legacy)
        legacy_migrated = True
        # Also remove the now-orphan `plugins/memory/` dir if it's empty
        # (it was created only because we wrote into it).
        legacy_parent = legacy.parent
        try:
            if not any(legacy_parent.iterdir()):
                legacy_parent.rmdir()
        except OSError:
            pass

    shim_dir = _shim_path(hermes_home)
    shim_dir.mkdir(parents=True, exist_ok=True)

    init_file = shim_dir / "__init__.py"
    init_file.write_text(SHIM_INIT_PY.format(version=__version__), encoding="utf-8")

    # Also drop a plugin.yaml so Hermes' optional metadata reader is happy.
    plugin_yaml = shim_dir / "plugin.yaml"
    plugin_yaml.write_text(
        f"""name: memex
version: {__version__}
description: Verbatim local-first memory for Hermes Agent. Pip-installed; this folder is a shim that delegates to the memex_hermes package.
pip_dependencies: []
""",
        encoding="utf-8",
    )

    # Try importing the real package right now to surface install issues
    # immediately instead of at Hermes startup.
    try:
        from memex_hermes import MemexMemoryProvider  # noqa: F401
        _ok = "OK"
    except ImportError as e:
        _ok = f"WARNING: cannot import memex_hermes ({e}). Run `pip install memex-hermes` first."

    print(f"✅ memex-hermes shim installed at: {shim_dir}")
    print(f"   • {init_file}")
    print(f"   • {plugin_yaml}")
    print(f"   • Python import check: {_ok}")
    if legacy_migrated:
        print(f"   • Migrated from legacy 0.1.0 path: {legacy}")

    # v0.1.5: auto-backfill is default-on. Pulls Hermes' pre-install history
    # from ~/.hermes/state.db into memex.db so that a first `memex search`
    # right after install can find old conversations — the wow moment.
    # Opt-out via `memex-hermes init --no-backfill`.
    skip_backfill = bool(getattr(args, "no_backfill", False))
    state_db = hermes_home / "state.db"

    print()
    if skip_backfill:
        print("ℹ️  History backfill skipped (--no-backfill).")
        print("   To import later:  memex-hermes-backfill")
    elif not state_db.exists():
        print("ℹ️  No Hermes history found yet (state.db absent).")
        print("   Live capture will start with your next Hermes session.")
    else:
        print("📥 Importing your Hermes history into memex.db...")
        try:
            # Lazy import to avoid circular dep at module load.
            from memex_hermes.backfill import run_backfill

            since_arg = getattr(args, "since", None)
            memex_db_arg = getattr(args, "memex_db", None)
            totals = run_backfill(
                hermes_home=str(hermes_home),
                memex_db=memex_db_arg,
                since=since_arg,
                dry_run=False,
                verbose=False,
            )
            print(f"   • sessions processed:  {totals.get('sessions', 0)}")
            print(f"   • new messages added:  {totals.get('inserted', 0)}")
            print(f"   • already in memex:    {totals.get('skipped', 0)} (deduped)")
            if totals.get("errors"):
                print(f"   • ⚠️  errors:            {totals['errors']} (non-fatal — live capture still works)")
            if totals.get("inserted", 0) > 0:
                print(f"   ✨ Try it: `memex search \"...\"`")
        except Exception as e:  # noqa: BLE001
            # Backfill is non-essential for init — failures must not block
            # plugin install. Live capture works regardless.
            print(f"   ⚠️  Backfill failed: {e}")
            print(f"      Live capture will still work. Retry later: memex-hermes-backfill")

    print()
    print("Next steps:")
    print(f"   1. Add to ~/.hermes/config.yaml:")
    print(f"        memory:")
    print(f'          provider: "memex"')
    print(f"   2. Restart Hermes Agent so the plugin gets picked up.")
    print(f"      (typical: `systemctl --user restart hermes`")
    print(f"       or:      `pkill -HUP -f hermes-agent`)")
    return 0


def cmd_uninstall(args: argparse.Namespace) -> int:
    """Remove the shim folder. Does NOT uninstall the pip package itself."""
    hermes_home = _resolve_hermes_home(args.hermes_home)
    shim_dir = _shim_path(hermes_home)
    legacy = _legacy_shim_path(hermes_home)

    removed_any = False
    if shim_dir.exists():
        shutil.rmtree(shim_dir)
        print(f"✅ Removed shim at {shim_dir}")
        removed_any = True
    if legacy.exists():
        shutil.rmtree(legacy)
        print(f"✅ Removed legacy 0.1.0 shim at {legacy}")
        removed_any = True

    if not removed_any:
        print(f"Nothing to uninstall — no shim at {shim_dir} (or legacy path).")
        return 0
    print("   The pip package memex-hermes is still installed.")
    print("   To remove that too: `pip uninstall memex-hermes`")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """Report current shim status — installed? where? version match?"""
    hermes_home = _resolve_hermes_home(args.hermes_home)
    shim_dir = _shim_path(hermes_home)
    init_file = shim_dir / "__init__.py"

    print(f"Hermes home:    {hermes_home}")
    print(f"Hermes exists:  {hermes_home.exists()}")
    print(f"Expected shim:  {shim_dir}")
    print(f"Shim installed: {init_file.exists()}")
    print(f"pip package:    memex-hermes v{__version__}")

    if init_file.exists():
        content = init_file.read_text(encoding="utf-8")
        if "memex-hermes plugin shim" in content:
            print("Shim content:   recognised (auto-generated)")
        else:
            print("Shim content:   present but NOT auto-generated — leaving as-is")
    return 0


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="memex-hermes",
        description=(
            "Manage the memex-hermes Hermes plugin shim. "
            "(Hermes discovers plugins by folder, not by pip entry_points.)"
        ),
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--hermes-home",
        default=None,
        help="Path to Hermes home dir (default: $HERMES_HOME or ~/.hermes)",
    )

    p_init = sub.add_parser(
        "init",
        parents=[common],
        help=(
            "Create the shim folder so Hermes can discover the plugin, "
            "and auto-import pre-install history from ~/.hermes/state.db. "
            "Use --no-backfill to skip history import."
        ),
    )
    p_init.add_argument(
        "--no-backfill",
        action="store_true",
        help="Skip the automatic import of pre-install Hermes history.",
    )
    p_init.add_argument(
        "--since",
        default=None,
        help=(
            "When importing history, include only sessions after this date "
            "(YYYY-MM-DD or unix epoch). Default: import full history."
        ),
    )
    p_init.add_argument(
        "--memex-db",
        default=None,
        help="Override memex.db location. Default: ~/.memex/data/memex.db",
    )
    p_init.set_defaults(func=cmd_init)

    p_uninstall = sub.add_parser(
        "uninstall",
        parents=[common],
        help="Remove the shim folder. Doesn't uninstall the pip package.",
    )
    p_uninstall.set_defaults(func=cmd_uninstall)

    p_status = sub.add_parser(
        "status",
        parents=[common],
        help="Report whether the shim is installed and where.",
    )
    p_status.set_defaults(func=cmd_status)

    args = parser.parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":
    sys.exit(main())
