"""Install / uninstall the Hermes plugin shim.

Hermes Agent discovers plugins by **scanning folders** at:
  • <hermes_agent>/plugins/memory/<name>/   (bundled)
  • ~/.hermes/plugins/<name>/                (user-installed)

It does NOT use pip entry_points — verified empirically against Hermes
v0.10.x by reading plugins/memory/__init__.py (the loader has zero
references to importlib.metadata). So just `pip install memex-hermes`
is not enough — Hermes won't see the plugin.

This module ships a thin CLI (`memex-hermes init`) that creates the
required folder + a 3-line shim file that imports from the pip-installed
package. Benefits:

  • Auto-updates: `pip install -U memex-hermes` upgrades the plugin on
    next Hermes restart, without re-running init.
  • Tiny footprint in ~/.hermes/: just a stub, all real code in pip
    site-packages.
  • Passes Hermes' textual scan (looks for `register_memory_provider`
    OR `MemoryProvider` in __init__.py).

If Hermes adds entry_points support later, the pyproject.toml entry
point declaration is already there for free — no work needed at that
time.
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Optional

from memex_hermes import __version__

log = logging.getLogger(__name__)


SHIM_DIR_NAME = "memex"  # folder name → also the plugin name Hermes sees.

SHIM_INIT_PY = '''"""memex-hermes plugin shim — auto-generated by `memex-hermes init`.

DO NOT EDIT. Re-run `memex-hermes init` to refresh.

This 3-line shim is what Hermes' folder-based plugin discovery loads.
The real implementation lives in the pip-installed `memex_hermes`
package. `pip install -U memex-hermes` upgrades the plugin without
re-running init — the shim picks up the new code automatically.

Hermes textual scan: this file mentions MemoryProvider (via
MemexMemoryProvider import) and register_memory_provider (in this
docstring and in the body of register() below) so the discovery
filter accepts it.
"""

from memex_hermes import register  # noqa: F401
from memex_hermes.provider import MemexMemoryProvider  # noqa: F401

# Generated by memex-hermes v{version}
'''


def _resolve_hermes_home(explicit: Optional[str] = None) -> Path:
    """Find Hermes home dir — explicit arg > $HERMES_HOME > default ~/.hermes/."""
    candidate = (
        explicit
        or os.environ.get("HERMES_HOME")
        or "~/.hermes"
    )
    return Path(os.path.expanduser(candidate)).resolve()


def _shim_path(hermes_home: Path) -> Path:
    return hermes_home / "plugins" / "memory" / SHIM_DIR_NAME


def cmd_init(args: argparse.Namespace) -> int:
    """Create the shim folder + __init__.py inside ~/.hermes/plugins/memory/memex/.

    Idempotent: re-running is safe, just rewrites the file with the
    current version stamp.
    """
    hermes_home = _resolve_hermes_home(args.hermes_home)
    if not hermes_home.exists():
        print(
            f"ERROR: Hermes home not found at {hermes_home}.\n"
            "Install Hermes Agent first, or pass --hermes-home /path/to/your/hermes/home",
            file=sys.stderr,
        )
        return 2

    shim_dir = _shim_path(hermes_home)
    shim_dir.mkdir(parents=True, exist_ok=True)

    init_file = shim_dir / "__init__.py"
    init_file.write_text(SHIM_INIT_PY.format(version=__version__), encoding="utf-8")

    # Also drop a plugin.yaml so Hermes' optional metadata reader is happy.
    plugin_yaml = shim_dir / "plugin.yaml"
    plugin_yaml.write_text(
        f"""name: memex
version: {__version__}
description: Verbatim local-first memory for Hermes Agent. Pip-installed; this folder is a shim that delegates to the memex_hermes package.
pip_dependencies: []
""",
        encoding="utf-8",
    )

    # Try importing the real package right now to surface install issues
    # immediately instead of at Hermes startup.
    try:
        from memex_hermes import MemexMemoryProvider  # noqa: F401
        _ok = "OK"
    except ImportError as e:
        _ok = f"WARNING: cannot import memex_hermes ({e}). Run `pip install memex-hermes` first."

    print(f"✅ memex-hermes shim installed at: {shim_dir}")
    print(f"   • {init_file}")
    print(f"   • {plugin_yaml}")
    print(f"   • Python import check: {_ok}")
    print()
    print("Next steps:")
    print(f"   1. Add to ~/.hermes/config.yaml:")
    print(f"        memory:")
    print(f'          provider: "memex"')
    print(f"   2. Restart Hermes.")
    print(f"   3. (Optional) Backfill history: `memex-hermes-backfill`")
    return 0


def cmd_uninstall(args: argparse.Namespace) -> int:
    """Remove the shim folder. Does NOT uninstall the pip package itself."""
    hermes_home = _resolve_hermes_home(args.hermes_home)
    shim_dir = _shim_path(hermes_home)
    if not shim_dir.exists():
        print(f"Nothing to uninstall — no shim at {shim_dir}.")
        return 0
    shutil.rmtree(shim_dir)
    print(f"✅ Removed shim at {shim_dir}")
    print("   The pip package memex-hermes is still installed.")
    print("   To remove that too: `pip uninstall memex-hermes`")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """Report current shim status — installed? where? version match?"""
    hermes_home = _resolve_hermes_home(args.hermes_home)
    shim_dir = _shim_path(hermes_home)
    init_file = shim_dir / "__init__.py"

    print(f"Hermes home:    {hermes_home}")
    print(f"Hermes exists:  {hermes_home.exists()}")
    print(f"Expected shim:  {shim_dir}")
    print(f"Shim installed: {init_file.exists()}")
    print(f"pip package:    memex-hermes v{__version__}")

    if init_file.exists():
        content = init_file.read_text(encoding="utf-8")
        if "memex-hermes plugin shim" in content:
            print("Shim content:   recognised (auto-generated)")
        else:
            print("Shim content:   present but NOT auto-generated — leaving as-is")
    return 0


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="memex-hermes",
        description=(
            "Manage the memex-hermes Hermes plugin shim. "
            "(Hermes discovers plugins by folder, not by pip entry_points.)"
        ),
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--hermes-home",
        default=None,
        help="Path to Hermes home dir (default: $HERMES_HOME or ~/.hermes)",
    )

    p_init = sub.add_parser(
        "init",
        parents=[common],
        help="Create the shim folder in ~/.hermes/plugins/memory/memex/ so Hermes can discover the plugin.",
    )
    p_init.set_defaults(func=cmd_init)

    p_uninstall = sub.add_parser(
        "uninstall",
        parents=[common],
        help="Remove the shim folder. Doesn't uninstall the pip package.",
    )
    p_uninstall.set_defaults(func=cmd_uninstall)

    p_status = sub.add_parser(
        "status",
        parents=[common],
        help="Report whether the shim is installed and where.",
    )
    p_status.set_defaults(func=cmd_status)

    args = parser.parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":
    sys.exit(main())
